name: Build Windows

on:
  push:
    branches-ignore:
      - 'coverityScan'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: '${{ matrix.os }} (msvc ${{ matrix.arch }})'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        os:
          # windows-2019 is incompatible with substrate's constexpr array
          # see https://developercommunity.visualstudio.com/t/Crash-on-constexpr-creation-of-a-std::ar/1547919
          - windows-2022
        arch:
          - 'amd64'
          # - 'x86'
      fail-fast: false
    steps:
      - name: Runtime environment
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          Add-Content $env:GITHUB_PATH "$HOME/.local/bin"
          "GITHUB_WORKSPACE=$(pwd)" >> $env:GITHUB_ENV
          "PKG_CONFIG_PATH=$HOME/deps/lib/pkgconfig,$HOME/deps/share/pkgconfig" >> $env:GITHUB_ENV
          "CMAKE_PREFIX_PATH=$HOME/deps" >> $env:GITHUB_ENV
          "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1" >> $env:GITHUB_ENV
      - name: Setup compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64
      - name: Install OpenCppCoverage
        if: github.repository == 'dragonCodecs/libAudio'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install OpenCppCoverage
      - name: Setup OpenCppCoverage
        if: github.repository == 'dragonCodecs/libAudio'
        run: |
          echo "C:\Program Files\OpenCppCoverage" >> $GITHUB_PATH
      - name: Checkout libAudio
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout public deps
        shell: bash
        run: |
          git submodule init deps/pkgconf deps/openal-soft
          git submodule update --depth 1
      - name: Setup Meson + Ninja
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja
        working-directory: ${{ runner.temp }}
      - name: Setup pkgconf
        run: |
          meson setup build --prefix=$HOME/.local -Dtests=disabled
          meson compile -C build
          meson install -C build
          "PKG_CONFIG=$(where.exe pkgconf.exe)" >> $env:GITHUB_ENV
          Remove-Item $(where.exe pkg-config.bat)
          Remove-Item $(where.exe pkg-config)
        working-directory:  ${{ github.workspace }}/deps/pkgconf
      - name: Version tools
        run: |
          cl /Bv
          link
          cmake --version
          meson --version
          ninja --version
          & "$env:PKG_CONFIG" --version
      - name: Configure
        run: meson setup build --prefix=$HOME/.local
      - name: Build
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: meson install -C build
      - name: Run coverage build
        if: github.repository == 'dragonCodecs/libAudio'
        run: |
          Remove-Item -Recurse build
          Remove-Item deps/libcuefile.wrap
          Remove-Item deps/libreplaygain.wrap
          meson setup build --prefix=$HOME/.local -Db_coverage=true --buildtype=debug
          meson compile -C build
          meson test -C build
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/build/meson-logs
            ${{ github.workspace }}/build/test
          retention-days: 5
      - name: Codecov
        if: success() && github.repository == 'dragonCodecs/libAudio'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-windows-msys2:
    name: '${{ matrix.os }} (${{ matrix.sys }})'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        os:
          - windows-2022
        sys:
          - mingw64
          - ucrt64
          - clang64
      fail-fast: false
    steps:
      - name: Use MinGW from MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          path-type: inherit
          pacboy: >-
            toolchain:p
            lcov:p
      - name: Runtime environment
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=`pwd`" >> $GITHUB_ENV
      - name: Setup compiler
        if: startsWith(matrix.sys, 'mingw') || startsWith(matrix.sys, 'ucrt64')
        run: |
          echo "GCOV=gcov" >> $GITHUB_ENV
      - name: Setup compiler
        if: startsWith(matrix.sys, 'clang')
        run: |
          echo "GCOV=llvm-cov gcov" >> $GITHUB_ENV
      - name: Checkout libAudio
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout public deps
        shell: bash
        run: |
          git submodule init deps/pkgconf deps/openal-soft
          git submodule update --depth 1
      - name: Setup Meson + Ninja + gcovr
        shell: bash
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja gcovr
        working-directory: ${{ runner.temp }}
      - name: Version tools
        run: |
          cc --version
          c++ --version
          $GCOV --version
          meson --version
          ninja --version
      - name: Install dependencies
        run: |
          pacboy -S --noconfirm openal:p libogg:p libvorbis:p opus:p opusfile:p libopusenc:p flac:p \
            wavpack:p libmpcdec:p faac:p faad2:p libmad:p libid3tag:p
      - name: Configure
        run: meson setup build --prefix=$HOME/.local $BUILD_OPTS
      - name: Build
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: meson install -C build
      - name: Run coverage build
        if: github.repository == 'dragonCodecs/libAudio'
        run: |
          rm -rf build
          meson setup build --prefix=$HOME/.local -Db_coverage=true --buildtype=debug
          meson compile -C build
          meson test -C build
          ninja -C build coverage-xml
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}-${{ matrix.sys }}
          path: ${{ github.workspace }}/build/meson-logs/*
          retention-days: 5
      - name: Codecov
        if: success() && github.repository == 'dragonCodecs/libAudio'
        uses: codecov/codecov-action@v4
        with:
          directory: ./build/meson-logs/
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
