name: Build Linux

on:
  push:
    branches-ignore:
      - 'coverityScan'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: '${{ matrix.os.id }} (${{ matrix.compiler }})'
    runs-on: ${{ matrix.os.id }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - { id: ubuntu-22.04, name: jammy }
          - { id: ubuntu-24.04, name: noble }
        compiler:
          - 'gcc'
          - 'clang-18' # Use a specific version for now as the packaging on the snapshots got messed up again
      fail-fast: false
    steps:
      - name: Runtime environment
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=`pwd`" >> $GITHUB_ENV
      - name: Setup GCC
        if: startsWith(matrix.compiler, 'gcc')
        run: |
          CXX=${CC/#gcc/g++}
          sudo apt-add-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install $CC $CXX
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "GCOV=${CC/#gcc/gcov}" >> $GITHUB_ENV
        env:
          CC: ${{ matrix.compiler }}
      - name: Setup Clang
        if: startsWith(matrix.compiler, 'clang')
        run: |
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          rm llvm-snapshot.gpg.key
          sudo apt-add-repository "deb https://apt.llvm.org/${{ matrix.os.name }}/ llvm-toolchain-${{ matrix.os.name }}${CC/#clang/} main"
          sudo apt-get update
          sudo apt-get install $CC llvm
          CXX=${CC/#clang/clang++}
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "GCOV=/usr/bin/llvm-cov gcov" >> $GITHUB_ENV
        env:
          CC: ${{ matrix.compiler }}
        working-directory: ${{ runner.temp }}
      - name: Remove old LLVM plugins
        if: matrix.compiler == 'clang'
        run: |
          sudo apt purge llvm-{12,13,14,15}-linker-tools || true
      - name: Checkout libAudio
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout crunch
        uses: actions/checkout@v4
        with:
          repository: dragonmux/crunch
          path: deps/crunch
          #ref: TODO: need to feed what version of crunch to use in here..
          lfs: true
          submodules: true
      - name: Upgrade pip + wheel
        if: matrix.os.name == 'jammy'
        shell: bash
        run: |
          sudo python3 -m pip install --upgrade pip setuptools wheel
      - name: Setup Meson + Ninja + gcovr
        run: |
          sudo python3 -m pip install --break-system-packages meson ninja gcovr
        working-directory: ${{ runner.temp }}
      - name: Version tools
        run: |
          $CC --version
          $CXX --version
          $GCOV --version
          meson --version
          ninja --version
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install libopenal-dev libogg-dev libvorbis-dev libopus-dev libopusfile-dev \
            libflac-dev libwavpack-dev libmpcdec-dev libfaac-dev libfaad-dev libmad0-dev libid3tag0-dev
        #  libgl-dev qtbase5-dev
      - name: Install crunch
        shell: bash
        run: |
          meson build --prefix=/usr -Dsubstrate:default_library=static $BUILD_OPTS
          meson compile -C build
          sudo meson install -C build
        working-directory: ${{ env.GITHUB_WORKSPACE }}/deps/crunch
      - name: Configure
        run: meson setup build --prefix=$HOME/.local
      - name: Build
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: meson install -C build
      - name: Run coverage build
        if: success() && github.repository == 'dragonCodecs/libAudio'
        # Codecov no longer parses gcov files automatically
        run: |
          rm -rf build
          meson setup build --prefix=$HOME/.local -Db_coverage=true --buildtype=debug
          meson compile -C build
          meson test -C build
          gcovr -r . -x -o `pwd`/build/meson-logs/coverage.xml -e `pwd`/deps -e `pwd`/test --exclude-directories `pwd`/build/deps
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os.id }}-${{ matrix.compiler }}
          path: ${{ github.workspace }}/build/meson-logs/*
          retention-days: 5
      - name: Codecov
        if: success() && github.repository == 'dragonCodecs/libAudio'
        uses: codecov/codecov-action@v4
        with:
          directory: ./build/meson-logs/
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
