name: C++ CI

on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        compiler:
          - 'clang-5.0'
          - 'clang-6.0'
          - 'clang-7'
          - 'clang-8'
          - 'clang-9'
          - 'gcc-5'
          - 'gcc-6'
          - 'gcc-7'
          - 'gcc-8'
          - 'gcc-9'
        coverage: [false]
    steps:
 #     - name: Setup Python
 #       uses: actions/setup-python@v1
 #       with:
 #         python-version: 3.6.9
      - name: Compiler environment
        shell: bash
        run: "echo ::set-env name=PATH::$HOME/.local/bin:$PATH"
        env:
          CC: ${{ matrix.compiler }}
      - name: Coverage environment
        env:
          COVERAGE: 0
        run: echo "Coverage enabled for build? ${{ matrix.coverage }}"
      - name: Setup GCC
        if: startsWith(matrix.compiler, 'gcc')
        shell: bash
        run: |
          sudo apt-add-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y $CC ${CC/#gcc/g++}
          echo "::set-env name=CXX::${CC/#gcc/g++}"
      - name: Setup Clang
        if: startsWith(matrix.compiler, 'clang')
        shell: bash
        run: |
          sudo apt-add-repository "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic${CC/#clang/} main"
          sudo apt-get update
          export CC=${CC%.0}.0
          sudo apt-get install -y $CC ${CC/#clang/clang++}
          echo "::set-env name=CC::$CC"
          echo "::set-env name=CXX::${CC/#clang/clang++}"
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: libAudio
          lfs: true
#      - name: Checkout submodules
#        shell: bash
#        run: |
#          authHeader="$(git config --local --get http.https://github.com/.extraheader)"
#          git submodule sync --recursive
#          git -c "http.extraheader="$authHeader" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Setup Meson + Ninja
        shell: bash
        run: |
          echo $PATH
          wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
          pip3 install --user meson
          unzip ninja-linux.zip -d ~/.local/bin
          rm -f get-pip.py ninja-linux.zip
        working-directory: ${{ runner.temp }}
      - name: Version tools
        shell: bash
        run: |
          $CC --version
          $CXX --version
          [ $COVERAGE -ne 0 ] && $GCOV --version || true
          meson --version
          ninja --version
      - name: Configure
        run: meson build --prefix=$HOME/.local -Db_coverage=${{ matrix.coverage }}
      - name: Build
        run: ninja
        working-directory: ${{ env.GITHUB_WORKSPACE }}/libAudio/build
      - name: Test
        run: ninja test
        working-directory: ${{ env.GITHUB_WORKSPACE }}/libAudio/build
      - name: Install
        run: ninja install
        working-directory: ${{ env.GITHUB_WORKSPACE }}/libAudio/build

#  build-windows:
#    runs-on: ${{matrix.os}}
#    strategy:
#      matrix:
#        os: [windows-2019, windows-2016]
